---
title: "Class Schedule"
author: "Bruce Cochrane"
date: "August 3, 2015"
output: html_document
---

###  Introduction

#### Classes

1. (8/24) Organization and overview - Whales?
2.  (8/26)The historical Record.  
3.  (8/28)  Conception/misconception discussion

#### Reading

Chapters 1 & 2
Padian

#### Online

Darwin and Wallace
Correct the statement assignment

### The Physical Record

1.  (8/31)Chemistry and Physics
2.  (9/2) Overview of geological history
3.  (9/4) Reading a paper or somesuch (if not, perhaps taxonomy workshop)

#### Reading

Chapter 3
Radiometric dating

#### Online

Dating California

### Common Descent and Phylogenies

1.  (9/9) Intro - characters; using fossils
2.  (9/11) Trees and the carnivore example
3.  (9/14)  Class exercise; review
4.  (9/16)  EXAM

#### Reading

Chapter 4 

#### Online

Tetrapods and Titkaalik
The Origin of Birds

### Evolutionary Genetics

1. (9/18) The Background
2.  (9/21)  HW Essentials
3.  (9/23)  Stochastic Processes
4.  (9/25)  Selection
5.  (9/28)  Quantitative Genetics


#### Reading 

Chapters 5-7; some of 8

#### Online

Noor videos

#### Assignments

Hardy Weinberg Problems

### Case Studies in Evolution

1.  What we need to show (1-2 examples)
2.  Followup on examples?

#### Online

1.  Anoles
2.  Sticklebacks
3.  Mice

### Molecular and Developmental Evolution

1.  The basics
2.  Some fun things we've learned
3.  Molecules and Selection
4.  Devo I
5.  Devo II
### Sex and Sexual Selection

1.  Why Sex
2.  Sexual Selection - The behaviors
3.  Sexual selection - physiology

#### Online

Vrijenhoek - importance of sex
PBS - Sexual selection

### Speciation and Macroevolution

1.  Species overview
2.  Problem cases - sympatric and microbes
3.  Macroevolution
4.  Extinction

#### Online

Birth and death of species
Anoles II.

### Coevolution and Behavior

1.  Patterns of Coevolution
2.  
### Human Evolution

1.  The big picture
2.  The genus Homo
3.  Modern evolution





