---
title: <center>Comments on The Language of Evolution</center>
author: <center>Bruce Cochrane</center>
date: <center>`r format(Sys.Date(),format="%B %d %Y")`</center>
output: 
    html_document:
       css: Chapter.css
       toc: yes
       toc_depth: 5
---
### Introduction

Below you will find selected statements from the class, with my comments added in red.  Following the 5-6 statements selected from the class discussion, you will find my best shot at rephrasing each statement

### Horseshoe crabs have resisted the force of evolution.


1. Horseshoe crabs have not undergone evolution.   
<font color=#99000>Not true.  All organisms evolve; in this case that evolution has not been manifest in morphological change</font>
2. Horseshoe crabs have been well suited for their environment despite change over geologic time.  
<font color=#99000>Because the lineage has persisted, this is a reasonable hypothesis.  However, we know that environments change. So why no change in appearance?</font>
3. The horseshoe crab that we know today has been the most capable of survival and reproduction among the multiple variants that have arisen in the millions of years in which horseshoe crabs have existed.  
<font color=#99000>This is a pretty good statement of the procsess that all organisms have undergone.  However, it does not address why morphological change has been minimal.</font>  
4. There is no force of evolution to resist.  
<font color=#99000>This is absolutely true - evolution is not a "force".  However, it does not address the issue of the horseshoe crab</font>  
5.  Horseshoe crabs have many traits that have resisted change through evolution due to their usefulness.  
<font color=#99000>Traits cannot "resist change"</font>  

<font color=#99000> *Over the period of time reflected in the fossil record, the evolution of horseshoe crabs has resulted in a relatively small amount of morphological change* </font>

### Evolution has progressed from single-celled organisms to modern man.


1.   *Homo Sapiens*, like single cell organisms, are descended from a basal organism to fill their current niche(s.)  
<font color=#99000> OK, although "common ancestor" would be better than "basal organism".  I would also delete "to fill their current niches."</font>  
2.   Evolution has developed single celled organisms into present day men.
<font color=#99000>"Evolution" should never be followed by an active verb.  This makes it sound as though evolution has a plan, which it most certainly does not</font>  
3.  Evolution has produced more complex organisms as time has passed.  
<font color=#99000>See comments for statement 2</font>  
4. Evolution has gradually occurred to progress from single-celled organisms to modern man.  
<font color=#99000>Evolution is not progressive</font>
5. Evolution means to improve organisms over time and so it has led to the the "present-day" man from single-celled organisms.  
<font color=#99000>Evolution is not about "improvement"</font>

<font color=#99000>*All organisms, including single celled organisms and man, have descended from a common ancestor, and each possesses a unique suite of derived (as opposed to ancestral) traits*</font>

  

### Bacteria develop resistance to antibiotics.


1.  Bacteria can mutate when introduced to antibiotics in order to build resistance.  
<font color=#99000>This implies that mutations somehow result from exposure to antibiotics.  In fact, mutation is a random process that occurs independently of exposure to a selective agent</font>  
2.  Some bacteria change their composition so they can still infect hosts without being killed by antibiotics. The ones who survive pass on their genes lead to more affective bacteria.  
<font color=#99000>This implies that individual bacteria have the ability to become resistant in response to the antibiotic.  That is not the case.</font>  
3. Bacteria that are not resistant to antibiotics are killed, leaving only bacteria that survive the treatment of antibiotic which pass down the resistance to new generations.   
<font color=#99000>This is a fairly accurate statement regarding the process of selection </font>  
4. Bacteria evolved resistance to antibiotics  
<font color=#99000> True.  This is much better wording than the original.  However, see below for an improvement. </font>  
5. Bacteria exploited an opportunity to manifest immunity to antibiotics.  
<font color=#99000> No.   This implies that individual bacteria made a choice </font>

<font color=#99000> *Exposure to antibiotics has resulted in the evolution of resistance in bacteria.* </font>

### Individuals with the most offspring have the highest fitness.


1.  Individuals with the highest ability to survive long enough to eventually produce offspring have the highest fitness.  
<font color=#99000>  This only true if that ability is heritable - that is, that his or her offspring inherit whatever traits that contribute to survival </font>  
2.  Individuals with the most offspring who live to reproduce have the highest fitness.  
<font color=#99000> See the comment on answer 1 </font>  
3.  Individuals with the most offspring have passed on more advantageous features to their offspring that are better adapted than others who lack them.  
<font color=#99000> This is ok, only I would change the wording a bit.  I would say that it would be individuals who "have the most offspring and pass on adaptive traits"</font>  
4. Number of offspring does not determine fitness, but the quality of the offspring.   
<font color=#99000> What do we mean by "quality"?</font>
5.  Having more offspring does not increase fitness.  
<font color=#99000> By itself true.  But if so, then what does determine fitness?</font>  
6. Individuals who are most fit are the most likely to survive to produce offspring.  
<font color=#99000> Again, see the comments on answer 1.</font>  

### Insect wings evolved for flight.


1. Insect wings developed the ability of flight 
<font color=#99000> This implies that the wings themselves directed the process</font>  
2.  Insects wings were likely derived from thermal exchange structures. 
<font color=#99000> Interesting concept; it would need to be carried a little farther to address why this happened </font>  
3.  The ancestors of present-day insects utilized wings for flight  
<font color=#99000> True, but if one were to go far enough back in the insect lineage, this would not be true.</font>  
4.  Insect wings adapted when the opportunity for flight arose, when a new lineage of insect was formed. 
<font color=#99000> Pretty good, but needs wordsmithing.  The opportunity for flight has always been there; what arose (presumably) was an adaptive advantage that flight conferred.</font>  
5.  Insects evolved wings which allows them to fly. 
<font color=#99000> Organisms don't "evolve" structures; rather, structures arise as the result of evolution. </font>

<font color=#99000> *Wings may have evolved in insects as a result of an adaptive advantage conferred by flight.* </font>


### Evolution is just a theory


1.  Evolution is still technically a theory, but is supported by most everyone of the scientific community.  
<font color=#99000>Two problems here.  First of all, evolution *is* a scientific theory, not just *technically* one.  Second, and more importantly, science is not politics - the validity of any theory, hypothesis or model is *not* determined by the number of supporters it has.</font>
2.  Evolution is a theory-- meaning it is scientifically accepted, supported by a great deal of evidence, and, despite facing many challenges, has yet to be proven wrong.  
<font color=#99000>This is pretty good.  My only quibble with it is the use of the words "proven wrong".  A better one would be "falsified"</font> 
3. The principle of evolution is made up of many dimensions and patterns, processes, observations, and hypotheses. This means that the theory of evolution is testable. 
<font color=#99000>This is all true, however the reader may be left wondering what is meant by all of these dimensions.  It is absolutely true that hypotheses generated from the theory of evolution are testable.</font>
4.  Evolution is descent with modification.  
<font color=#99000>This is one piece of the evolutionary theory.  The second is the mechanism, natural selection, by which it appears</font>  
5.  Evolution is a theory.  
 <font color=#99000>This doesn't really say anything, since we still do not know what is meant by a theory</font>
 
<font color=#99000> *Evolution is a scientific theory; as such it is an overarching concept that leads to testable hypotheses about patterns and processes underlying the diversity of life.*</font> 