---
title: <center></center>
author: <center></center>
date: <h3>`r format(Sys.Date(),format="%B %d %Y")`</h3>
output: 
    html_document:
       css: Overview.css
---


Below is a link to an excellent paper, published in 2011, that covers much of the material in this unit.  It is fairly long, but concentrate on pp 159-171.   As you prepare for the second midterm exam (and for the final) you should look through it, focus on what it says about the following questions and relate it back to what we've covered.  **Do not simply quote or paraphrase the paper.** Rather, you should be able to bring in ideas, arguments and examples from other sources.

1. Why do "phenotypes matter"?
2. What are reaction norms?  How do they relate to phenotypic plasticity?
3. What's the problem with thinking about adaptation in terms of single gene effects?
4. How do standing genetic variation and new mutation differ in terms of their evolutionary impact?
5.  The authors argue that "selection ovewhelms drift."
Why?
