---
title: <center></center>
author: <center></center>
date: Updated `r format(Sys.Date(),format="%B %d %Y")`
output: 
    html_document:
       css: Overview.css
---
### Overview and Objectives

So now that we've covered (at least in theory) the genetic basis for evolutionary change, we need to turn our attention to evolution in the field.  To consider any such example, we need to consider that at the phenotypic level:

1.  Variation must exist
2.  It must be heritable
3.  Particular variants confer an adaptive advantage

Having established those conditions, we can then turn to addressing the genetic basis for the variation and determine if allele frequency dynamics of the gene(s) involved are consistent with predictions based on population genetic theory.

Chapter 8 covers a number of examples; we may mention of few of these in class.  However, we will not have specific classes devoted to this material; rather you will examine these concepts in the context of the paper assignment associated with the module.  We will discuss this in class on September 30.  Material from this module will **not** be included in the second mid-term exam.



