---
title: <center></center>
author: <center></center>
date: Updated `r format(Sys.Date(),format="%B %d %Y")`
output: 
    html_document:
       css: Overview.css
---
### Overview and Objectives

In this module, we will first introduce the evolutionary process by considering the whale (see pp. 5-15 of chapter 1).  We will then pose a simple question: *Why do biologists constantly refer to Charles Darwin?*  We will address that point, framing everything that follows in the course, by carefully examining the key elements of Darwinian Theory.  We will consider:

1.  The state of biological knowledge prior to Darwin
2.  The career of Darwin
3.  The logical development of *The Origin of Species*
4.  The two pillars of evolutionary theory
5.  Correct and incorrect intpretations and applications of evolutionary theory

### Class Topics

Class number|Date|Topic
---|---|---
1.|August 24|Introduction to the Course
2.|August 26|Whales and Darwin
3.|August 28|Conceptions and Misconceptions about evolution

### Preparation

Date|Required
---|---
8/24|Chapter 1 pp. 5-16; 22-24
8/26|Chapter 2; The Origins of Evolutionary Theory; The Evolution of the Whale
8/28|Padian (see below)

