---
title: <center></center>
author: <center></center>
date: Updated `r format(Sys.Date(),format="%B %d %Y")`
output: 
    html_document:
       css: Overview.css
---
### Overview and Objectives

We are going to finish the course on one subject Darwin avoided in *On the Origin of Species* - where do humans fit in the evolutionary picture?  We have touched on this occasionally during the course (remember the use of transposon insertions as derived characters to resolve the human-gorilla-chimpanzee trichotomy, for instance), but it is obviously a subject that warrants its own treatment.

As we consider the question, we will incorporate many of the approaches we have talked about throughout the semester, notably the integration of genetic and paleontological methods to make inferences about both common descent and the role played by natural selection in human evolution.  We'll try to be somewhat flexible when the time to cover this module approaches, but the general outline we are likely to follow is

1.  What do we know about the common ancestor of humans and chimpanzees?  When and where did it exist, and what was it?
2.  When and where did our genus (*Homo*) arise, and what is its history?
3.  When and where did *Homo sapiens* arise, how did it spread, and what is its phylogenetic relationship with other members of the genus?
4.  What can the genetics of modern populations tell us about population structure and natural selection in modern humans.

Note that the assignment for this module will be a light-hearted one - you will get to watch clips of movies that make evolutionary assertions and comment on their veracity.

### Class Topics

Class|Date|Topic
---|---|---
1.|November 30|Homonids and Homonins
2.|December 2|The Genus Homo
3.|December 4|Evolution in Modern *Homo sapiens*


### Preparation

Date|Required
---|---
11/30|Chapter 17 pp. 573-585
12/2|Chapter 17 pp. 588-596
12/4|Chapter 17 pp. 604-609; selected topics from Chapter 18
