---
title: <center>Wallace and Darwin</center>
author: <center></center>
date: <center>`r format(Sys.Date(),format="%B %d %Y")`</center>
output: 
    html_document:
       css: Chapter.css
---
### Introduction

Darwin is often given sole credit for the development of the theory of evolution by natural selection, and indeed he deserves much of it.  However, as is often the case in science, the discovery was not solely his.  In this video, we learn not only about Darwin's story, but also that of Alfred Russel Wallace, a less well known, but very important contemporary of Darwin's.


=======
Add on a little text just to test

=======

### Questions

1.  "Why were these forms created for such little apparent purpose?"
2.  Carefully compare and contrast the observations of Wallace and Darwin.  In particular, how did Darwin's observations in the Galapagos differ from those of Wallace in the Malay Archipelago?
2.  Why do you think Dr. Carroll mentions that Darwin found that "armadillo tastes like duck"?
3.  If you were to boil the Darwin/Wallace hypothesis down to two short statements, what would they be
4.  

<iframe width="100%" height="320" src="https://www.youtube.com/embed/XOiUZ3ycZwU" frameborder="0" allowfullscreen></iframe> 
### One final note

Dr. Carroll's description of the parallel explorations of Darwin and Wallace is excellent.  However, if one actually looks at what was communicated to the Linnean Society (see reference below) one finds that it was not a co-authored paper in the modern sense.  Rather, it was a communication (read by J. D. Hooker and Charles Lyell - Wallace and Darwin weren't even present), consisting of three separate parts:

1.  The first, written by Darwin, is an excerpt from the origin of species.
2.  The second is the text of a letter from Darwin to Asa Gray, a prominent naturalist of the time.
3.  The third is Wallace's contribution, entitled *On the Tendency of Varieties to depart indefinitely from the Original Type*.

Thus, while it is certainly true that they released their findings jointly, they did so in a way that separated their contributions from one another.
<<<<<<< HEAD

=======
>>>>>>> 7e15aefffd7269fe204e6d4fad71f0debf9fddfd
### Text References

### Other references
[Darwin and Wallace, 1858](http://wallacefund.info/content/1858-darwin-wallace-paper)  
